--[[ Eastern Grey Squirrel -- generated by tools/write_definitions.py

    Three stages on the vanilla "mouse" skeleton and animation set: kwc_squirrelkit,
    kwc_squirrelfemale and kwc_squirrelmale.

    The two adults SHARE a mesh and differ only in size, which is what vanilla
    does for raccoon, rat and mouse, and what the real animal does too -- there is
    no fox equivalent of antlers. The baby has its own mesh because a juvenile is
    not a scaled-down adult.

    Behaviour is inherited wholesale from the donor species by copying its table,
    so this starts out behaving like a mouse and differs in what you see and how
    big it is. Sounds, butchering yields and inventory icons are still the
    donor's.

    Regenerate with:
        python3 tools/write_definitions.py --out <mod>/media
]]

require "Definitions/animal/MouseDefinitions"

AnimalDefinitions = AnimalDefinitions or {};
AnimalDefinitions.animals = AnimalDefinitions.animals or {};
AnimalDefinitions.stages  = AnimalDefinitions.stages  or {};
AnimalDefinitions.breeds  = AnimalDefinitions.breeds  or {};

local GROUP   = "kwc_squirrel";
local TEXTURE = "KWC_Squirrel";

local BABY   = "kwc_squirrelkit";
local FEMALE = "kwc_squirrelfemale";
local MALE   = "kwc_squirrelmale";

local function shallowCopy(t)
    local out = {};
    for k, v in pairs(t) do out[k] = v; end
    return out;
end

local adultSrc = AnimalDefinitions.animals["mouse"];
local babySrc  = AnimalDefinitions.animals["mousepups"] or adultSrc;
if not adultSrc then
    print("[" .. GROUP .. "] donor 'mouse' not found; is MouseDefinitions loaded?");
    return;
end

-- Sounds hang off the BREED, not the animal -- vanilla does
-- `animals["raccoonboar"].breeds["grey"].sounds = raccoon_sounds`. Building a
-- fresh breed without one therefore makes the animal completely silent, which is
-- exactly what the first version of this file did.
--
-- So the donor's table is inherited wholesale, which gets the right keys and
-- slots for this skeleton for free (raccoon uses walkFront/walkBack, rat uses a
-- single idle_walk plus scuttle sounds), and only the four voice entries are
-- redirected to ours.
local function inheritSounds(donorId, overrides)
    local out = {};
    local src = AnimalDefinitions.animals[donorId];
    local base = nil;
    if src and src.breeds then
        for _, b in pairs(src.breeds) do
            if b.sounds then base = b.sounds; break; end
        end
    end
    if base then
        for k, v in pairs(base) do out[k] = v; end
    else
        print("[" .. GROUP .. "] donor '" .. tostring(donorId) ..
              "' had no sounds; this animal will be silent");
    end
    for key, spec in pairs(overrides) do
        local e = {};
        if out[key] then for kk, vv in pairs(out[key]) do e[kk] = vv; end
        else e.slot = "voice"; end
        for kk, vv in pairs(spec) do e[kk] = vv; end
        out[key] = e;
    end
    return out;
end

-- The intervals matter as much as the clips. See INTERVAL in
-- tools/write_definitions.py for why the donor's 10-20s idle is wrong here.
local adultSounds = inheritSounds("mouse", {
    idle     = { name = "KWC_SquirrelAdult_Idle",     intervalMin = 120, intervalMax = 320 },
    stressed = { name = "KWC_SquirrelAdult_Stressed", intervalMin = 35, intervalMax = 90 },
    pain     = { name = "KWC_SquirrelAdult_Pain" },
    death    = { name = "KWC_SquirrelAdult_Death" },
});
local babySounds = inheritSounds("mousepups", {
    idle     = { name = "KWC_SquirrelBaby_Idle",     intervalMin = 120, intervalMax = 320 },
    stressed = { name = "KWC_SquirrelBaby_Stressed", intervalMin = 35, intervalMax = 90 },
    pain     = { name = "KWC_SquirrelBaby_Pain" },
    death    = { name = "KWC_SquirrelBaby_Death" },
});

-- Breeds carry the texture and the sounds, so this species needs its own set
-- rather than the donor's. The two adults share a coat; the baby differs only in
-- which voice it uses.
-- Start from the donor's breed rather than an empty table. A vanilla breed carries
-- more than a texture -- rottenTexture, and the inventory icons for alive, dead and
-- skeletal states -- and anything left unset simply has no texture to draw. Ours
-- overrides what it has its own art for and inherits the rest, so a rotting or
-- picked-up critter still renders something instead of nothing.
local function breedFrom(donorId, sounds)
    local base = nil;
    local src = AnimalDefinitions.animals[donorId];
    if src and src.breeds then
        for _, b in pairs(src.breeds) do base = b; break; end
    end
    local out = {};
    if base then for k, v in pairs(base) do out[k] = v; end end
    out.name          = "default";
    out.texture       = TEXTURE;
    out.textureMale   = TEXTURE;
    -- No separate rotting art yet, so point it at our own coat. Left unset it
    -- would fall through to the donor's, and a rotting squirrel would turn rat.
    out.rottenTexture = TEXTURE;
    out.sounds        = sounds;
    return out;
end

AnimalDefinitions.breeds[GROUP] = { breeds = {
    default = breedFrom("mouse", adultSounds),
} };

local babyBreeds = { default = breedFrom("mousepups", babySounds) };

-- This species' OWN stages. Pointing at the donor's would grow the baby into a
-- mouse.
AnimalDefinitions.stages[GROUP] = { stages = {
    [BABY]   = { ageToGrow = 60, nextStage = FEMALE, nextStageMale = MALE },
    [FEMALE] = { ageToGrow = 60 },
    [MALE]   = { ageToGrow = 60 },
} };

-- Stage 1 aggression (see tools/write_definitions.py). Data only: whether this
-- animal can fight, at what range and how often. No targeting lives here, and
-- nothing scans for a victim -- that is stage 2 of STATUS 7g.
--
-- The donor sets NO attack field at all, so without this the animal simply
-- cannot fight. attackTimer is a cooldown and LOWER IS FASTER; vanilla runs
-- mouse 1500, sow 2000, hen 3500, ewe 6000, cow 8200. attackDist 0 is vanilla's
-- way of saying harmless (mouse, rat, chick, turkeypoult).
--
-- Babies never fight, matching chick/turkeypoult/mousepups.
local ADULT_AGGRO = { dist = 0, timer = 1500,
                      back = false, stressed = false };
local BABY_AGGRO  = { dist = 0, timer = 4000, back = false, stressed = false };

local function define(id, src, model, minSize, maxSize, minWeight, maxWeight, male, breeds, aggro)
    local a = shallowCopy(src);
    a.bodyModel = model;
    a.breeds    = breeds or AnimalDefinitions.breeds[GROUP].breeds;
    a.stages    = AnimalDefinitions.stages[GROUP].stages;
    a.group     = GROUP;
    -- Our own animation set, not the donor's. The donor has no attack state at
    -- all, so a provoked predator walked up to its target and stood there --
    -- damage comes from an AttackConnect event inside the attack ANIMATION, not
    -- from the attack stats. Generated by tools/write_animsets.py, which also
    -- makes m_SpeedScale per-species: three canids of different sizes were all
    -- moving on raccoon timings.
    a.animset   = GROUP;
    a.minSize   = minSize;
    a.maxSize   = maxSize;
    a.minWeight = minWeight;
    a.maxWeight = maxWeight;
    a.male      = male or false;
    a.wild      = true;
    if aggro then
        a.attackDist       = aggro.dist;
        a.attackTimer      = aggro.timer;
        a.attackBack       = aggro.back;
        a.attackIfStressed = aggro.stressed;
    end
    -- Designation zones silently domesticate-and-de-wild animals every ~2000
    -- ticks, nulling their migration group. A wild critter must never be
    -- eligible.
    a.canBeDomesticated = false;
    AnimalDefinitions.animals[id] = a;
    return a;
end

define(BABY,   babySrc,  "KWC_SquirrelKit", 0.326, 0.496, 0.05, 0.25, false, babyBreeds, BABY_AGGRO);
define(FEMALE, adultSrc, "KWC_Squirrel", 0.562, 0.627, 0.4, 0.65, false, nil, ADULT_AGGRO);
define(MALE,   adultSrc, "KWC_Squirrel", 0.588, 0.653, 0.42, 0.7, true,  nil);

-- Breeding pairs, and what a newborn is. Set AFTER all three exist so the ids
-- resolve.
AnimalDefinitions.animals[FEMALE].mate     = MALE;
AnimalDefinitions.animals[MALE].mate       = FEMALE;
AnimalDefinitions.animals[FEMALE].babyType = BABY;
AnimalDefinitions.animals[MALE].babyType   = BABY;
AnimalDefinitions.animals[BABY].mate       = nil;
AnimalDefinitions.animals[BABY].babyType   = nil;
